name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - run: pnpm install

      - name: Compile app
        uses: x6pnda/action-electron-compiler@v1.0.2
        with:
          package_manager: PNPM
          package_root: apps/ui
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
